---
- hosts: all
  become: yes
  become_method: sudo

# ensure the latest apt packages for Ubuntu 18.04 LTS

  tasks:
  - name: update to latest packages
    apt:
      upgrade: yes
      force_apt_get: yes
  
  - name: full-updated all packages
    apt:
      upgrade: full
      force_apt_get: yes
...